server:
  port: 8080  # 网页端口
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/goods_manage  # 数据库链接地址,最后的goods_manage是数据库名
    username: user  # 数据库用户名
    password: 123456  # 数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver  # 数据库连接类，gradle导入的
  thymeleaf:
    cache: false  # 禁止thymeleaf网页渲染的缓存，方便调试
    encoding: UTF-8  # 设定编码为UTF-8，保证中文正确显示
  servlet:
    multipart:
      max-file-size: 5MB  # 最大允许上传5MB的文件
logging:
  level:
    com.example.goodsmanage.mapper: trace  # 设置数据库操作的mapper类信息等级为trace，控制套会显示SQL命令方便调试，信息从多到少依次是 trace>debug>info>error，默认info